### PR TITLE
Updated link to official website

### PR DESCRIPTION
**Pull request by sangar**

### CODE REVIEW

**Comment by fhasex20** [comment]
Since tigal has some troubles, how are the chances that the Opentracker v2 production will be still going on                                                                                                                                                                                                                                                                                                                                        Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: Andrey SheykhotGesendet: Freitag, 27. März 2015 10:16An: TIGAL/OpenTrackerAntwort an: TIGAL/OpenTrackerBetreff: Re: [OpenTracker] Updated link to official website (#13)Merged #13.

—Reply to this email directly or view it on GitHub.

**Comment by opensourcegps** [comment]
Hello, please rest assured that production of OpenTracker is going forward. Unfortunately, we can not use Tigal brand anymore.

All new PCB and software files will be published at: https://github.com/geolink/opentracker

We are already in progress of ordering new OpenTracker batch, please bear with us during our complications with previous hardware partner. I apologize for any inconvenience this might cause.

**Comment by fhasex20** [comment]
Hi,Will there be a major rework of the pcb? Is CAN-Bus now officially working?So far,Ferdinand                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Von: Andrey SheykhotGesendet: Freitag, 27. März 2015 10:30An: TIGAL/OpenTrackerAntwort an: TIGAL/OpenTrackerCc: fhasex20Betreff: Re: [OpenTracker] Updated link to official website (#13)Hello, please rest assured that production of OpenTracker is going forward. Unfortunately, we can not use Tigal brand anymore.

All new PCB and software files will be published at: https://github.com/geolink/opentracker

We are already in progress of ordering new OpenTracker batch, please bear with us during our complications with previous hardware partner. I apologize for any inconvenience this might cause. 

—Reply to this email directly or view it on GitHub.

**Comment by opensourcegps** [comment]
No major rework, we are looking into adding SD card and CAN-Bus issues to be fixed. Also there might be extension board with more sensors.

**Comment by fhasex20** [comment]
Sd-card would be super, Expansion Board with accelerometer would also be nice (to get some metrics about driving behavior), maybe you might consider replacing the rp-sma Sockets against fakra Sockets since these plugs are automotoive Standard (at least for trucks)So far,                                                                                                                                                                                                                                                                                                                                        Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: Andrey SheykhotGesendet: Freitag, 27. März 2015 10:42An: TIGAL/OpenTrackerAntwort an: TIGAL/OpenTrackerCc: fhasex20Betreff: Re: [OpenTracker] Updated link to official website (#13)No major rework, we are looking into adding SD card and CAN-Bus issues to be fixed. Also there might be extension board with more sensors. 

—Reply to this email directly or view it on GitHub.

**Pull request merged**
